application:
  version: 1.0.0
  title: Walk Planet

#Server
Server:
  host: localhost
  port: 8030
  servlet:
    context-path: /walkplanet
    session:
      tracking-modes: cookie
#  error:
#    path:  #????? ??? ??
#    include-exception: false
#    include-stacktrace: never
#    whitelabel:
#      enabled: true

spring:
  profiles:
    active: local
  servlet:
    multipart:
      enabled: true
      max-file-size: 200MB
      max-request-size: 200MB
  datasource:
    url: jdbc:log4jdbc:postgresql://kichani.com:5433/kichandb
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    username: postgres
    password: gg0069
    hikari.connection-timeout: 60000
    hikari.maximum-pool-size: 2
#   Hibernate
  jpa:
    properties:
      hibernate:
        default_batch_fetch_size: 1000
        dialect: org.hibernate.dialect.PostgreSQL10Dialect
        ddl-auto: update
        #ddl-auto: create
        #ddl-auto: create-drop
        #ddl-auto: update
        #        ddl-auto: validate
        show_sql: true
        format_sql: true
  #        sql: true
  #        use_sql_comments: true
  jackson:
    serialization:
      fail-on-empty-beans: false
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration
  thymeleaf:
    #    prefix: file:src/main/resource/webapp/WEB-INF/templates/
    #    suffix: .html
    mode: HTML
    cache: false
    template-resolver-order: 0
    #check-template-location: true
  devtools:
    livereload:
      enabled: true
    restart:
      enabled: true
      poll-interval: 2s`
      quiet-period: 1s

  jwt:
    secret: UVBzSnZsVV9pLWdvMDFfclNZVVJjZEgwQklzZGtTdTBGRDdkLVcyZjJrYUpKcmhKdUpMMVBIWmlDNThINzVmNTNqWWVVWGlzTGlIYy1GWVkyeTFEdkE=
    #${JWT_ENCODE}
#linux jwt secret
#export JWT_SECRET=QPsJvlU_i-go01_rSYURcdH0BIsdkSu0FD7d-W2f2kaJJrhJuJL1PHZiC58H75f53jYeUXisLiHc-FYY2y1DvA

#window jwt secret
#setx JWT_SECRET "QPsJvlU_i-go01_rSYURcdH0BIsdkSu0FD7d-W2f2kaJJrhJuJL1PHZiC58H75f53jYeUXisLiHc-FYY2y1DvA"
#setx JWT_ENCODE "UVBzSnZsVV9pLWdvMDFfclNZVVJjZEgwQklzZGtTdTBGRDdkLVcyZjJrYUpKcmhKdUpMMVBIWmlDNThINzVmNTNqWWVVWGlzTGlIYy1GWVkyeTFEdkE="
logging:
  file:
    name: ./logs/admin
    max-history: 365
    max-size: 100MB
  level:
    org:
      springframework: INFO
      hibernate:
        SQL: debug
        type: trace
  main:
    banner-mode: console

#임의로 경로 설정
domain:
  file: HOOXIADMIN1.5\src\main\resources\static\img
file:
  upload-dir: C:/uploads/
